format_version: 10
pipelines:
  TestOne:
    group: AT20Group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-5737a45:
        git: https://github.com/AT20-DevOps/AT20_ADMISSION_SERVICE.git
        username: esthervasquez
        shallow_clone: false
        auto_update: true
        branch: task9
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit-test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - hello
                - word
                command: echo
                run_if: passed
          code_coverage:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -la
                command: ls
                run_if: passed
    - code-inspection:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sonar:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - sonar-scanner command here
                command: echo
                run_if: passed
